### ISSUE TITLE
Can't access to the admin panel

### ISSUE THREAD

**Issue by corentincharron** [benyanke/docker-taiga#11]
Hello!

Thanks for the script, it's very useful. On my server, it seems to be working except that I can't access to the admin panel.

Maybe that's due to my special case: In the same docker-compose, I build a Nginx reverse proxy, that distributes requests to the different services, such as Taiga. So I can access to Taiga, I can create projects, but when I want to go to https://mydomain/admin, I get "_Not Found. The requested URL /admin was not found on this server."_

Here is my docker-compose.yml:
```
version: '3'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - '/srv/reverseproxy/config/:/etc/nginx/'

  taiga:
    image: benyanke/taiga:latest
    container_name: taiga
    depends_on:
      - postgres
      - proxy
    environment:
      TAIGA_HOSTNAME: mydomain
      TAIGA_DB_HOST: postgres
      TAIGA_DB_NAME: taigadb
      TAIGA_DB_USER: taiga
      TAIGA_DB_PASSWORD: password
      TAIGA_SSL_BY_REVERSE_PROXY: 'True'

    volumes:
      - '/srv/taiga/media:/usr/src/taiga-back/media'
      - '/srv/taiga/conf:/taiga'

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: taigadb
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: password
    ports:
      - '5432'
    volumes:
      - '/srv/postgres/:/var/lib/postgresql/data'
```

My reverse proxy's nginx.conf

```
worker_processes 1;

events { worker_connections 1024; }

http {

    sendfile on;

    upstream taiga {
        server taiga:80;
    }

    server {
        listen 80;
        server_name mydomain;
        return 301 https://mydomain$request_uri;
    }

    server {
        listen 443 ssl;
        server_name mydomain;

        ssl_certificate        /etc/nginx/mydomain.pem;
        ssl_certificate_key    /etc/nginx/server-key.pem;

        location / {
            proxy_pass         http://taiga;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }
    }
}
```

Thanks a lot
